import regex

# BAR_CODE

PROFILE_IDENTIFIER_MAX_LENGTH = 14
PROFILE_IDENTIFIER_MIN_LENGTH = 8
PROFILES_MAX_COUNT = 50
PROFILE_CHAR_VALUE_MAX_COUNT = 15

PROFILE_IDENTIFIER_REGEX = regex.compile(r"^[A-Z0-9\-\_/()\s]+$")


# SHELF_NUMBER
SHELF_NUMBER_MAX_LENGTH = 25
SHELF_NUMBER_MIN_LENGTH = 1

SHELF_NUMBER_REGEX = regex.compile(r"^\d+$")


# IMAGES
IMAGES_MAX_COUNT = 5
