import regex

CATALOG_ENTRY_VARIANT_CHAR_VALUES_MAX_COUNT = 15


# VENDOR CODE
VENDOR_CODE_MAX_LENGTH = 24
VENDOR_CODE_MIN_LENGTH = 5

VENDOR_CODE_REGEX = regex.compile(r"^[\p{IsCyrillic}\p{IsLatin}0-9 _\-\(\)/]+$")
