from anbor_types import ListQuery, Query

class WarehouseInventoryOverviewQuery(Query): ...

class WarehouseInventoryCategoryFlowQuery(Query): ...

class WarehouseInventoryTopSellingQuery(ListQuery): ...