from anbor_types import ListQuery, Query


class InventoryAnalyticsOverviewQuery(Query): ...


class InventoryAnalyticsCategoryFlowQuery(Query): ...


class InventoryAnalyticsLiquidQuery(ListQuery): ...


class InventoryAnalyticsIlliquidQuery(ListQuery): ...
