# Promotion
PROMOTION_NAME_MAX_LENGTH = 100
PROMOTION_NAME_MIN_LENGTH = 3


# TAG
TAG_TEXT_COLOR_MIN_VALUE = 1
TAG_TEXT_COLOR_MAX_VALUE = 33

TAG_BG_COLOR_MIN_VALUE = 1
TAG_BG_COLOR_MAX_VALUE = 33

TAG_ICON_MIN_VALUE = 1
TAG_ICON_MAX_VALUE = 33
